title: FHIR MCP Server Documentation
description: >-
  Comprehensive documentation for the FHIR MCP Server - a powerful Model Context Protocol
  server for FHIR R4 with interactive elicitation, real-time notifications, validation,
  and intelligent healthcare workflows.

baseurl: "/fhir-mcp" # the subpath of your site, e.g. /blog
url: "https://martijn-on-fhir.github.io" # the base hostname & protocol for your site

# Repository information
repository: martijn-on-fhir/fhir-mcp

# Theme - using default GitHub Pages themes for compatibility
theme: minima

# Navigation links
header_pages:
  - index.md
  - quick-start-guide.md
  - server-notifications.md
  - fhir-operations.md
  - interactive-elicitation.md
  - healthcare-workflows.md
  - api-reference.md
  - troubleshooting.md

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: en-US
author:
  name: FHIR MCP Server Team
  email: noreply@github.com

# Social links (for SEO)
social:
  name: FHIR MCP Server
  links:
    - https://github.com/martijn-on-fhir/fhir-mcp

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Collections for better organization
collections:
  wiki:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "wiki"
    values:
      layout: "page"